spring:
  application:
    name: @project.name@
    version: @project.version@
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
      ddl-auto: none 
  output:
    ansi:
      enabled: always
server:
  port: 8080 
management:
  server:
    port: 8081
logging:
  level:
    root: INFO